### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bsommerfeld** [HInformatikAG/TetrisSwing#1]
Wenn man einen TetrominoBlock am Rand dreht, dann ist es möglich den Block aus dem Spielfeld zu schieben.

**Comment by olaf1789** [comment]
Das ist richtig, aber auch bekannt, es gibt dafür ein TODO in der Klasse Spiel.java
Die Ursache ist eine bisher nicht implementierte Methode zur Prüfung: public boolean passtGedrehterSpielstein(TetrominoSpielstein spielstein)
Das Implementieren dieser Methode habe ich als Extraaufgabe verfasst (siehe Codekommentar), für die SchülerInnen, die den Rest schon fertig haben.
